name: Build And Push to ECR and Ecs

on: 
    push:
        # pull_requests: 
        #     branches: ['main', 'dev']
        branches: [ 'main']

permissions:
  id-token: write
  contents: read

jobs:
    Build_scan:
        runs-on: ubuntu-latest
        steps:
           - name: checkout code
             uses: actions/checkout@v7
           - name:   Trivy Scan
             uses: aquasecurity/trivy-action@v0.36.0
             with:
                scan-type: 'fs'
                severity: HIGH,CRITICAL
                exit-code: 1 
           - name:  Build image
             run: docker build -t ${{ secrets.ECR_REPO }}/portfolio-ecr:latest .    
           
           - name: Scan image with Trivy 
             uses: aquasecurity/trivy-action@v0.36.0
             with: 
                image-ref: ${{ secrets.ECR_REPO }}/portfolio-ecr:latest
                format: table 
                exit-code: 0
                ignore-unfixed: true 
                severity: CRITICAL,HIGH
           
           - name: Configure AWS credentials
             uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
             with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                aws-region: us-east-1
           - name: Login to Amazon ECR
             id: login-ecr
             uses: aws-actions/amazon-ecr-login@v2     
            

           - name: push Image to Ecr
             run: docker push ${{ secrets.ECR_REPO }}/portfolio-ecr:latest

    Deploy_to_Ecs:
        needs: Build_scan
        runs-on: ubuntu-latest   
        steps:
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            - name: Deploy to Amazon ECS
              uses: aws-actions/amazon-ecs-deploy-task-definition@v2
              with:
                 task-definition: myapp-task
                 service: myapp-service
                 cluster: myapp-cluster
                 wait-for-service-stability: true       