name: Build And Push to ECR

on: 
    push:
        # pull_requests: 
        #     branches: ['main', 'dev']
        branches: [ 'main']

jobs:
    build_scan:
        runs-on: ubuntu-latest
        steps:
           - name: checkout codee
             uses: actions/checkout@v7
           - name:   Trivy Scan
             uses: aquasecurity/trivy-action@v0.36.0
             with:
                scan-type: 'fs'
                severity: HIGH,CRITICAL
                exit-code: 1 
           - name:  Build image
             run: docker build -t 196135431738.dkr.ecr.us-east-1.amazonaws.com/portfolio-ecr:latest .    
           
           - name: Scan image with Trivy 
             uses: aquasecurity/trivy-action@v0.36.0
             with: 
                image-ref: 196135431738.dkr.ecr.us-east-1.amazonaws.com/portfolio-ecr:latest
                format: table 
                exit-code: 1
                ignore-unfixed: true 
                severity: CRITICAL,HIGH
           -  name: Push image to Ecr
              run: echo "push"
            

  